-- // add table invites
-- Migration SQL that makes the change goes here.
CREATE TABLE invites (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id BIGINT NOT NULL DEFAULT 0,
	room_id BIGINT NOT NULL DEFAULT 0,
	inviter_id BIGINT NOT NULL DEFAULT 0,
	comment VARCHAR(255),
	is_accepted SMALLINT NOT NULL DEFAULT 0,
	is_rejected SMALLINT NOT NULL DEFAULT 0,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE NO ACTION,
	FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE NO ACTION,
	FOREIGN KEY (inviter_id) REFERENCES users(id) ON DELETE NO ACTION
)


-- //@UNDO
-- SQL to undo the change goes here.
DROP TABLE invites

