-- // add table roles
-- Migration SQL that makes the change goes here.
CREATE TABLE roles (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role VARCHAR(32) NOT NULL UNIQUE,
	
	PRIMARY KEY(id)
)


-- //@UNDO
-- SQL to undo the change goes here.
DROP TABLE roles